# Validate Python Application
#
# REFERENCES
#
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema
# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables

trigger:
  branches:
    include:
    - master
    - feature/*
    exclude:
    - test/*

pool:
  vmImage: 'ubuntu-latest'

steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'

  - script: |
      python --version
      pip --version
      pip install -r requirements.txt
    displayName: requirements

  - script: |
      yapf --version
      pylint --version
      yapf --style google --diff --parallel main.py setup.py employees/employees.py tests/testemployees.py
      pylint main employees.employees tests.testemployees
      python setup.py check
    displayName: check

  - script: |
      coverage run -m unittest --verbose
    displayName: test

  - script: |
      coverage report employees/employees.py
      coverage html -d cover employees/employees.py
    displayName: coverage

  - script: |
      python -m main -h
      python -m main --version
      python -m main -v tests/test.yaml
    displayName: run

  - script: |
      (cd docs; make html)
    displayName: docs

  - script: |
      python setup.py clean
      python setup.py sdist --dist-dir=target/dist
      python setup.py build --build-base=target/build
      cp $(System.DefaultWorkingDirectory)/target/dist/Employees-*.tar.gz $(Build.ArtifactStagingDirectory)
    displayName: dist

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/target/docs/html'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/docs-$(Build.BuildNumber).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: package
