# Validate Python Application
#
# REFERENCES
#
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema
# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

  - script: |
      sudo apt-get install make python python-dev python-coverage python-pip
      [[ ! -e /usr/bin/coverage ]] && sudo ln -sf /usr/bin/python-coverage /usr/bin/coverage
      sudo apt-get install python-nose python-nosehtmloutput python-pyflakes python-sphinx python-sphinx-rtd-theme pandoc
      sudo python -m pip install --upgrade pip
      sudo python -m pip install pycodestyle
    displayName: 'Install Project Dependencies'

  - script: |
      make all
    displayName: 'Make Project'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/target/docs/html'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'
      artifactName: docs

