# Validate Python Application
#
# REFERENCES
#
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema
# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'

  - script: |
      # requirements
      python --version
      pip --version
      pip install virtualenv
      virtualenv venv
      source venv/bin/activate
      pip install -r requirements.txt
      # check
      yapf --version
      pylint --version
      yapf --style google --diff --parallel main.py setup.py employees/employees.py tests/testemployees.py
      pylint main employees.employees tests.testemployees
      python setup.py check
      # test
      coverage run -m unittest --verbose
      # coverage
      coverage report employees/employees.py
      coverage html -d cover employees/employees.py
      # run
      python -m main -h
      python -m main --version
      python -m main -v tests/test.yaml
      # docs
      (cd docs; make html)
      mv target/docs/html ./public
      # dist
      python setup.py clean
      python setup.py sdist --dist-dir=target/dist
      python setup.py build --build-base=target/build
      mv target/dist/*.tar.gz ./public/
    displayName: build

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/public'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'
      artifactName: package
